### ISSUE TITLE
Setting scientific metadata

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scitacean#115]
In branch api-v4, as a user creating a new dataset, I should be able to set the scientific metadata for a dataset using the notation:
`dataset.meta = dict(properties)`

Current behavior:
When I try to set the metadata on an existing dataset using the replace method, I receive an error stating that the attribute "meta" can not be set.

Expected behavior:
I should be able to set the scientific metadata with the following code:
```
modified_dataset = existing_dataset.replace(
  meta={
   "key1" : "value1",
   ...
  }
)
```

**Comment by jl-wynen** [comment]
Done on the branch
