### ISSUE TITLE
Support attachments

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/scitacean#126]
Need to find a good interface to expose attachments. One idea is:

```python
dset = client.get_dataset(...)
assert dset.attachments is Unset  # not initialised
attachments = client.fetch_attachments(dset) # or pass pid
# or
dset = client.with_fetched_attachments(dset)
assert dset.attchments == [ ... ] # all attachments stored as a list

dset = Dataset(...)
assert dset.attachments == []
dset.attachments.append(Attachment(...))
finalized = client.upload_new_dataset_now(dset)  # uploads attachments if the list is non-empty
```
We can also add an argument to `get_dataset` to immediately download the attachments.

when downloading w/o attachments, they are `Unset` in order to stop users from adding attachments and getting into an inconsistent state between the client and database (e.g., client as attachment A and dbase has [B, C]).

**Comment by nitrosx** [comment]
@jl-wynen this looks good and reasonable.
I would make the attachment functionality as similar as we can to the file download one.

**Comment by jl-wynen** [comment]
Done in #135
