### ISSUE TITLE
More relaxed validation of downloaded data

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/scitacean#134]
Currently, when downloading a model, Scitacean validates it the same way as during uploads. Since not all data in the database conforms to all requirements, Scitacean is slightly relaxed in that it falls back to constructing models without validation. But this uses `model_construct` from Pydantic with does not convert all fields to their proper types. So we can end up with difficult to use objects.

The user that downloads a model often has no way of fixing a broken entry in the database. So we should not make their life harder just because, e.g., some email address is broken.

I suggest to remove validations from download models altogether. I'm talking specifically about 'validation' in the strict sense not 'conversion' to, e.g., `RemotePath`, as Pydantic uses the term.

**Comment by YooSunYoung** [comment]
I agree, will it still have some sort of indicators or warnings about the broken parts so that users can easily fix them?

If it is because of the incompatible version of each model,
maybe it's enough to mention that it seems like a wrong version in the warning messages or somewhere visible.

**Comment by jl-wynen** [comment]
This doesn't actually seem to be a big issue anymore because `Dataset` now converts its fields itself. If this issue pops up again, please reopen and show concrete examples!
