### ISSUE TITLE
Use placeholder for release versions before release

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/scitacean#154]
When adding directives like `.. versionadded::`, we need to provide a version number. But this is impossible to predict in CalVer.
So use a placeholder version. And implement a check in the release workflow to look for placeholders and stop if it finds any. Also add a script to replace placeholders. (This should not run automatically to reduce the risk of breaking the code.)

In Scipp, we use `PLACEHOLDER` or `vPLACEHOLDER`. Is this good enough or should we use a different placeholder text?

**Comment by YooSunYoung** [comment]
I just used ``RELEASE_PLACEHOLDER`` in #153 

Cause it looked like [``prepare-release`` tox command](https://github.com/scipp/scipp/blob/main/tox.ini) uses this in scipp...?

```
[testenv:prepare-release]
description = Run before a release. Pass the release version as a positional argument.
skip_install = true
deps =
allowlist_externals = sh
commands =
  sh -c 'git grep -rl RELEASE_PLACEHOLDER docs/ src/scipp | xargs sed -i "s/RELEASE_PLACEHOLDER/{posargs}/g"'
```

**Comment by jl-wynen** [comment]
See also https://github.com/scipp/copier_template/issues/35
