### ISSUE TITLE
Test `SSHFileTransfer`

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/scitacean#25]
Use docker container

**Comment by jl-wynen** [comment]
Attempted to set this up using the `linuxserver/openssh-server` docker image. I can spin up the container and SSH into it from the command line. But paramiko and by extension fabric fail to connect. Currently, I am getting `paramiko.ssh_exception.SSHException: Error reading SSH protocol banner` when the container is started using the fixture. And I get an unknown host error when the container is started using the command line.

**Comment by nitrosx** [comment]
Can you elaborate more on what you are trying to achieve and test?

**Comment by jl-wynen** [comment]
There are currently no automated tests for `SSHFileTransfer`. So there is a high risk of this class breaking. I would like to have tests that download and upload files to a fileserver using `SSHFileTransfer`. But similarly to the backend, we cannot rely on a real server somewhere.

I think the easiest solution is to set up a container with a server that we have full control over. So the tests would start a container and then create instances of `SSHFileTransfer` with the proper URL and credentials to access that container. The easiest way to write tests with it is doing roundtrips, i.e. upload a file and then download again. If we want to test upload and download in isolation, we would need some alternative way of accessing the container and inspecting files.

Fabric does provide a test fixture for connections (https://docs.fabfile.org/en/stable/api/testing.html#module-fabric.testing.fixtures) but this would make it hard or impossible to test authentication. Since I had repeated problems with that, I would like to include it in the tests.

**Comment by nitrosx** [comment]
Thanks for clarifying it. I think it is worth have the test.
