### ISSUE TITLE
Make model validation warn when downloading

### ISSUE THREAD

**Issue by jl-wynen** [SciCatProject/scitacean#33]
Datasets may not always be 100% up the scitacean's requirements. E.g. a field may not be a valid email address. In this case, we should still download the dataset and display a warning. Right now, it raises an exception.

**Comment by nitrosx** [comment]
I agree. 
We should load it anyway and provide a property that is set to true if the item is scitacean validated.
Scitacean might have stricter validation rules than SciCat, or users may have a custom validation function

**Comment by jl-wynen** [comment]
Do you have a use case for a way to check if validation was successful? I would just emit a warning which users can handle or ignore.

**Comment by nitrosx** [comment]
Can you elaborate on which data you are looking for?
