### ISSUE TITLE
Clone dataset

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scitacean#50]
As a user, it would be efficient to have a clone method on a dataset to create a new one which is the exact copy of the original one, but with the necessary lifecycle properties reset, including pid.

**Comment by jl-wynen** [comment]
In addition, it would be good to have a `derive` method that makes a derived dataset which has the input as a parent.

The question here is what other attributes should be preserved? That is, are there any attributes that are always the same when you derive?
Alternatively, we could have an argument like `dset.derive(keep=['owner', 'proposal_id', ...])` to make it a bit easier to select what to carry over.
