### ISSUE TITLE
Files as generator

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scitacean#53]
I was wondering what are the benefits of having the files property of the dataset as a generator and not a simple list?
Now that it is a generator, I need to use a non-trivial syntax to retrieve a single file.

`file = list(dset_with_local_file.files)[0]`

**Comment by jl-wynen** [comment]
Files are spread out over datablocks. So they are held in a collection of several lists. `Dataset.files` hides this fact.
It could be changed to return a list, or better tuple (to avoid modification). This should not decrease performance in any relevant way as there typically are only a handful of files.

However, it is tempting to access files like you do in your example. But how do you know this is the correct file? Scitacean makes no promise about the order of files. So if you want to get the only file, you should be using `file, = dset_with_local_file.files`. If there are multiple, you need to select the file you want in some different way.
