### ISSUE TITLE
Investigator in derived dataset requires an email

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scitacean#54]
As a user, I would expect that investigator in derived datasets would be set to the name of the investigator.
Currently it requires an email.

**Comment by jl-wynen** [comment]
This follows the description here https://github.com/SciCatProject/backend/blob/36b8ef32a1e57e6c6e64f239a411187a46b657b3/common/models/derived-dataset.json#L18

If this is incorrect, we can remove the validation. But then we should also amend the model.

**Comment by nitrosx** [comment]
@jl-wynen: you are right and, even in the new backend, documentation says that it is the email of the (principal) investigator.
That said, we have been using it for the name of the (principal) investigator.
Let's place this issue on the back burner, while I talk to the collaborators and with the team
