### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scitacean#55]
When uploading a new dataset, the client upload the files and than create a new dataset object and validate this new dataset.
If there is any issue with the newly created dataset, user will receive a validation error, after the files have been uploaded.

As a user, I would expect to receive the validation errors before any upload happens.

**Comment by jl-wynen** [comment]
Good point! This needs to be fixed.

Unfortunately, this only helps with Scitacean's validation. The server might still reject the dataset. Is there a way to ask if a dataset is valid without creating it in the database?

**Comment by nitrosx** [comment]
In the new backend, we added an endpoint that validate the data model, but does not create the entry.
Unfortunately, in the old backend there is not such functionality.

**Comment by jl-wynen** [comment]
Ok. For now, let's validate locally before file upload. And add remote validation when possible.
