### ISSUE TITLE
Pydantic dependency

### ISSUE THREAD

**Issue by nitrosx** [SciCatProject/scitacean#73]
As a user, when I just install Scitacean and import it in a python script or jupyter notebook, I trigger the following error:
```
....
AttributeError: module 'pydantic' has no attribute 'Extra'
```

Once I install separately pydantic, the import is successful.

Is it possible to include pydantic as a dependency for Scitacean? or make sure that documentation highlight the dependency and. maybe, the reason why it is required to install it manually?

**Comment by jl-wynen** [comment]
pydantic is a dependency!
How did you install scitacean?
What version of pydantic do you have now and what did you have before?

**Comment by nitrosx** [comment]
I just realized that it is not an issue of missing dependency. 
Pydantic is indeed installed, but does not have the attribute Extra.

**Comment by nitrosx** [comment]
Pydantic is version 0.18.2 from conda-forge

**Comment by jl-wynen** [comment]
How did you do that?! This version is from 2019. Judging from a bit of digging around git blames of pydantic, `Extra` has existed for more than 1 year.

This might be an issue with some other dependency on your side.

**Comment by jl-wynen** [comment]
We can add a minimum version of 1.9 or so in Scitacean. But since I don't know a concrete version, this is just a guess.

**Comment by nitrosx** [comment]
Let me recreate the environment in conda

**Comment by nitrosx** [comment]
Recreating the environment from scratch and the order in which the packages were installed solved the issue.
The following order brought to the error indicated in this issue:
```bash
conda install jupyterlab
conda install -c conda-forge jupyterlab-h5web
conda install -c conda-forge scitacean
```
while with the following sequence, the environment does not show the error
```bash
conda install jupyterlab
conda install pydantic
conda install -c conda-forge jupyterlab-h5web
conda install -c conda-forge scitacean
```

**Comment by jl-wynen** [comment]
I tried this myself and installing `jupyterlab` and `jupyterlab-h5web` does not even install pydantic! Don't know where this came from.

Anyway, I added a minim version in the package config.
